import { HeaderLayout } from "@/app/ui/layout/HeaderLayout";
import { FooterLayout } from "@/app/ui/layout/FooterLayout";
import { Nunito } from "next/font/google";
import { ThemeProvider } from "@/context/ThemeContext";
import type { Metadata } from "next";
import "./globals.css";

const nunito = Nunito({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Comparador de Precios",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${nunito.className} antialiased grid grid-rows-[auto_1fr_auto] min-h-[100dvh]`}
      >
        <ThemeProvider>
          <HeaderLayout />
          <main>
            {children}
          </main>
          <FooterLayout />
        </ThemeProvider>
      </body>
    </html>
  );
}
